name: Deploy feature branches to nonproduction bucket

on:
  push:
    branches:
      - feature*
env:
  BUCKET_NAME: cfst-3457-f41211a0f566ff0153c7f08ab-nonprodbucket-d9afe39vu7i4
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build site
        run: |
          npm ci
          npm run build
      - name: deploy to bucket
        run: aws cp public s3://$ {{ env.BUCKET_NAME }}/ --recursive --acl public-read
